const GenericSkillQuestions =["Oral Communication",
                     "Written Communication",
                     "Process Conformance",
                     "Presentation Skills",
                     "Leadership Skills",
                     "Management",
                     "Interpersonal Skills",
                     "Takes initiative",
                     "Critical & Analytical Thinking",
                     "Demonstrates Teamwork",
                     "Adaptability & Flexibility",
                     "Customer Focus",
                     "Planning & organizing",
                     "Negotiation Skills",
                     "Problem Solving Skills"]
export default GenericSkillQuestions;
