const GenericSkillQuestions =["1. Oral Communication",
                     "2. Written Communication",
                     "3. Process Conformance",
                     "4. Presentation Skills",
                     "5. Leadership Skills",
                     "6. Management",
                     "7. Interpersonal Skills",
                     "8. Takes initiative",
                     "9. Critical & Analytical Thinking",
                     "10. Demonstrates Teamwork",
                     "11. Adaptability & Flexibility",
                     "12. Customer Focus",
                     "13. Planning & organizing",
                     "14. Negotiation Skills",
                     "15. Problem Solving Skills"]
export default GenericSkillQuestions;
