const Questions =["1. Add Test Case",
                     "2. Repeater",
                     "3. Refractor",
                     "4. Fail",
                     "5. CSUnit",
                     "6. DocTest",
                     "7. JUnit",
                     "8. Nunit",
                     "9. PHPUnit",
                     "10. PyUnit",
                     "11. Testing",
                     "12. Acceptance Testing",
                     "13. Selenium",
                     "14. Jira",
                     "15. Java",
                     "16. RSpec",
                     "17. Specflow",
                     "18. Low Level approach",
                    ]
export default Questions;