const TestDrivenQuestions = ["Add Test case",
    "Repeater",
    "Refactor",
    "Fail",
    "CSUnit",
    "DocTest",
    "JUnit",
    "Nunit",
    "PHPUnit",
    "PyUnit",
    "TestNG",
    "Acceptance Testing",
    "Selenium",
    "Jira",
    "Java",
    "RSpec",
    "Specflow",
    "Low Level approach"]
export default TestDrivenQuestions;
